#!/bin/sh

echo "\nCopying assets from Unity project to dev server...\n"
cp -r ~/Documents/unity.nosync/disk/MallGame_WebGL/* static/
echo "\nAssets copied.\n"

cp static/custom/index.html static/
cp static/custom/TemplateData/* static/TemplateData/

git st
git aa
git cm "Deployment tag: $2"

echo "\nPushing assets to [$1] server...\n"
git po
echo "\nAssets pushed.\n"

echo $(gcloud compute ssh instance-2 -- 'cd MallGameServer && git pull')
echo "\nConfiguring [$1] environment...\n"
case "$1" in
  prod)
    echo $(gcloud compute ssh instance-2 -- 'sudo service nginx restart')
    ;;
  dev)
    ;;
  *)
    ;;
esac

echo "\nDeployment finished.\n"
